apiVersion: apps/v1
kind: Deployment
metadata:
   name: voting-app-deploy
spec:
   replicas: 3
   selector:
     matchLabels: 
        app: vote
   template:
      metadata:
          name: voting-app-pod
          labels:
             app: vote
      spec:
         containers:
             - name: voting-app-container
               image: amitfegade121/vote:v1
               ports:
                 - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
   name: voting-app-svc
spec:
   selector:
      app: vote
   type: NodePort
   ports:
      - port: 3000
        targetPort: 80
        nodePort: 30000

