apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: voting-app-rs 
spec:
   replicas: 3
   selector:
     matchLabels: 
        app: vote
        version: v1
   template:      
      metadata:
         name: voting-app-pod 
         labels:	
             app: vote 
             version: v1
             tier: frontend 
     spec: 
        containers:
           - name: voting-app-container  
             image: amitfegade121/vote:v1
             ports:
                - containerPort: 80