apiVersion: v1
kind: Pod
metadata:
   name: voting-app-pod 
   labels:	
      app: vote 
spec: 
   containers:
     - name: voting-app-container  
       image: amitfegade121/vote:v2
       ports:
          - containerPort: 80
