apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  RDS_HOSTNAME: "mysql"
  RDS_PORT: "3306"
  RDS_DATABASE: "hr"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      name: employee-app
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app
          image: amitfegade121/spring-boot-employee-app:1.0
          ports:
            - containerPort: 8080
          env:
            - name: RDS_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: RDS_HOSTNAME
            - name: RDS_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: RDS_PORT
            - name: RDS_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: RDS_DATABASE

---
apiVersion: v1
kind: Service
metadata:
  name: employee-app
spec:
  selector:
    app: employee-app
  ports:
    - targetPort: 8080
      port: 8080
