apiVersion: v1
kind: Secret
metadata:
  name: mysql_secret
type: Opaque
data: MYSQL_ROOT_PASSWORD=cm9vdA==
  MYSQL_DATABASE=aHI=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selectors:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql_secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql_secret
                  key: MYSQL_DATABASE

---
apiVersion: v1
kind: Service
metadata:
  name: mysql_db_svc
spec:
  selectors:
    app: mysql
  ports:
    - targetPort: 3306
      port: 3306
